### ISSUE TITLE
SyntaxError: Unexpected identifier 'assert'

### ISSUE THREAD

**Issue by xuezier** [aliyun/alibabacloud-esa-cli#1]
刚装完运行就有问题

![image](https://github.com/user-attachments/assets/463efbfb-f141-4506-b326-fee838e3439b)

**Comment by xuezier** [comment]
![image](https://github.com/user-attachments/assets/51f5e30d-756a-4194-8ea0-770b0e674f14)
import 断言在 Node 22 已经移除了支持，改为了 with 关键字。这个特性不支持当前主流覆盖的所有 Node 版本，建议是移除这个断言方式，改为手动断言检测

**Comment by Kinice** [comment]
感谢您的issue和pr，我们使用了最新的node LTS版本开发（20.18.0），所以暂时没有发现这个写法的兼容性问题，十分感谢您能提出来！

**Comment by Kinice** [comment]
已经合并pr并发布新版本，再次感谢，希望您继续给我们提意见！
